from text_rewrite import TextRewrite


# sentences = ['My machine is so bad and dramatic', 'I have one dog and two cars', 'This season is so weak.', 'my home is so sucky']
sentences = ['A large and relatively colorful cisticola endemic to Kenya, found locally in montane grassland and moorland. The cap and back of the neck are dull rufous with darker streaking, the back is heavily streaked with black, and there is a rufous panel in the wings. As with other cisticolas, habitat and vocalizations are important to identification. Very similar to Stout Cisticola, but has streaking on the back of the neck. The common vocalizations are a quick series of several squeaky notes, and a series of lower liquid notes.'
,'Small shy warbler. Dull brown with a paler belly and brow stripe. Like most bush-warblers, difficult to see as it moves through dense foliage. Listen for its sweet song, consisting of a few introductory notes followed by two long whistles: “ti-ti-tchew weeeeee-cheeeeee’. Visually very difficult to separate from Yellowish-bellied Bush Warbler and Brownish-flanked Bush Warbler, and differences are extremely subtle. Himalayan breeders average more greenish on the back than either of the other two species, and have a strong yellow wash on the belly; Brownish-flanked, with which Aberrant overlaps in the eastern Himalayas, is much browner overall. In central China, Aberrant overlaps with Yellowish-bellied, which has a pale gray throat instead of a yellowish-buff one. Aberrant breeds in shrubby edge, bamboo stands, and open bushy areas in montane and hill areas; upper altitudinal limit averages higher than both Yellowish-bellied and Brownish-flanked.'
,'Large, plain, long-tailed sparrow. Drab grayish-brown overall, with dark mask like a Northern Cardinal. Also note pinkish bill and orange undertail coverts. Inhabits riparian corridors, especially in dense brush. Mainly occurs in the Sonoran Desert of Arizona, barely extending into surrounding states and northern Mexico. Rather secretive as it forages on the ground for seeds and insects. Visits feeders.'
,'An unusual and distinctive warbler of the Ethiopian highlands. Mostly gray with chestnut under the tail, a red eye, black between the eye and bill, and a white patch above the eye. Found in dry montane juniper and hagenia forest. Easily separated from other gray warblers by the dark gray underparts and rufous undertail. Sometimes skulking, but will sing in the open; the male’s song is an explosive, variable combination of musical, fluted notes, usually accompanied by low ratcheting from the female.'
,'Small, dark member of the waxbill family. The back is red, the wings and tail black, and the underparts gray. Males and females are similar, though males show a bit of red on the flanks. Found in montane forest, mainly in thick and wet areas such as along streams, including forest edge and glades. Inconspicuous bird that is usually found in pairs or small groups. The call is a high-pitched “tsit.” Similar in size and overall coloration to Red-faced Crimsonwing, but darker, and doesn’t show red or yellow on the face.'
,'A huge ground-dwelling hornbill. Males have a mix of blue and red bare facial skin, while females have entirely blue facial skin. In flight, a large white patch is revealed in the wings. Found in savanna, grassland, and agricultural habitats, usually in pairs or small groups, walking on the ground. Breeds and roosts in trees. Similar to Southern Ground-Hornbill, but there is little overlap in range, and Abyssinian is easily separated by the blue facial skin. The call is a series of deep “boop” notes.'
,'Large, brown-backed, orange-breasted thrush with bold white wingbars. Found in the understory of montane forest. Generally shy and scarce. The song is a musical and typically thrush-like, a chatty and cheerful series of whistles and chuckles. The call is a very thin, rising trill. Very similar to Orange Ground-Thrush, but has a different pattern on the head: an orange crown, a plain face, and a complete white eye-ring.'
,'A large and relatively colorful member of the pipit family. Note the black necklace, orange throat, and partially yellow eye-stripe. The white corners of the black tail are conspicuous during the weak, fluttering flight. Found on the ground in montane grassland, often in wet areas. Brownish immatures can be confused with pipits, but are larger and more robust. The vocalizations include “tsik” calls and whistles.'
]
for sentence in sentences:
    new_sentence = TextRewrite(sentence).work() 
    print(sentence + " -> " + new_sentence)
